config/routes.rb
EasyOrder::Application.routes.draw do
  root 'menus#index'
  resources :menus, only: [:index] do
    collection do
      get :products_by_category
    end
  end
end

app/models/category.rb
class Category
  include Mongoid::Document

  field :name, type: String
end

app/models/menu.rb
class Menu
  class << self
    def all_categories
      Category.all
    end

    def all_products
      Product.where(active: true)
    end

    def all_products_by_category(category)
      Product.where(category: category)
    end
  end
end

app/models/product.rb
class Product
  include Mongoid::Document

  field :name, type: String
  field :price, type: BigDecimal
  field :active, type: Boolean
  field :out_of_stock, type: Boolean
  field :picture_url, type: String

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
 def index
    @categories = Menu.all_categories
  end

  def products_by_category
    category = Category.find(params[:category_id])
    @products = Menu.all_products_by_category(category)
    render :json => {:data => @products, :status => :success}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyOrder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/index.html.erb
<h1>Menus#index</h1>
<ul>
  <% @categories.each do |category| %>
  <li><%= link_to category.name, products_by_category_menus_path(category_id: category.id) %></li>
  <% end %>
</ul>